# reboot serveur pterodactyl
name: Restart Discord Bot on Pterodactyl

on:
  push:
    branches:
      - dev  # Déclenche le workflow sur un push dans la branche principale

jobs:
  restart:
    runs-on: ubuntu-latest  # Exécute le workflow sur une machine Ubuntu

    steps:
      - name: Redémarrer le serveur Pterodactyl
        run: |
          curl -X POST "https://${{ vars.PTERO_PANEL_URL }}/api/client/servers/${{ vars.PTERO_SERVERS_ID_DEV }}/power" \
          -H "Authorization: Bearer ${{ secrets.PTERO_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"signal": "restart"}'
